### ISSUE TITLE
[Feature] VideoCall

### ISSUE THREAD

**Issue by RakunKo** [Say-Better/Android-Learner-APP#23]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Issue Overview
스프린트2 중 videocall 관련 이슈
솔루션 진행 캠 화면 표시

## Todo
- [x] 솔루션 진행 캠 화면 표시
- [x] 카메라 전환
- [x] 카메라 끄기/켜기
