### ISSUE TITLE
[Feature] 화상통화 종료 및 카메라/마이크 제어

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Learner-APP#32]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Issue Overview

- 화상통화에 대한 기본적인 제어를 지원하기 위한 기능을 개발합니다.

## Todo

- [x] 화상통화 종료 버튼 구현
- [x] 카메라, 마이크 on/off 구현
- [x] 카메라 전면/후면 전환 구현
- [x] 캠 화면 컴포저블 스타일 조정
