### ISSUE TITLE
[Feature] ChatBot 

### ISSUE THREAD

**Issue by RakunKo** [Say-Better/Android-Learner-APP#4]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Issue Overview
챗봇에 관한 UI, 기능

## Todo
- [x] UI
- [x] Hangul AutoMata (입력과정이 안보임 ㅜㅜ, 결과는 정상 출력), 해결
- [x] Symbol Layout
- [x] Input UI
- [x] 전체적인 비율 조정
