### ISSUE TITLE
[Feature] WebRTC 화상통화 기능 추가

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Learner-APP#8]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Issue Overview
WebRTC를 통해 인앱에서 화상통화를 구현합니다. 편의상 Learner-APP 사이의 화상통화를 구현하고 정상 동작을 확인 후 Educator-APP에도 동일한 기능을 추가 예정입니다.

## Todo
- [x] Firebase 앱 등록 및 데이터 Insert 테스트
- [x] 안드로이드 Foreground Service 활성화
- [x] Firebase listener 추가 및 테스트
- [x] 통화 요청 생성
- [x] 솔루션 진행 View 설정
- [ ] WebRTC Peer Connection
