### ISSUE TITLE
[Feature] 화상 통화

### ISSUE THREAD

**Issue by RakunKo** [Say-Better/Android-Learner-APP#9]
## Type of change

- [x] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Todo
- [x] 상징 터치 시 하이라이팅
- [x] 의사소통 기회 일때 log 저장
- [x] 상징 input 대기화면
- [x] TTS
- [ ] 비율 수정
